# Generated by Django 4.2.2 on 2023-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultitemmodel',
            name='vault_item_salt',
            field=models.CharField(default='66df2eaf283d7fc8ca69c00b20f22a4cd43a5a0c252a4416eac3def7f4713e7a', max_length=255),
        ),
    ]
