# Generated by Django 4.2.2 on 2023-06-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaultApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vaultitemmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='salt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaultApp.vaultusermodel'),
        ),
        migrations.AlterField(
            model_name='vaultitemmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaultApp.vaultusermodel'),
        ),
    ]
