# Generated by Django 4.2.2 on 2023-06-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaultApp', '0003_vaultitemmodel_id_alter_salt_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaultApp.vaultusermodel'),
        ),
        migrations.AlterField(
            model_name='vaultitemmodel',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaultusermodel',
            name='username',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
