# Generated by Django 4.2.2 on 2023-06-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaultApp', '0004_alter_salt_user_alter_vaultitemmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PepperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepper', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vaultApp.vaultusermodel')),
            ],
        ),
        migrations.AddField(
            model_name='vaultitemmodel',
            name='salt',
            field=models.CharField(default='50e99920db11d12cb56b94f926c11d15f1d3324c5b7260dcfcd8584d84df535f', max_length=255),
        ),
        migrations.DeleteModel(
            name='Salt',
        ),
    ]
